version: '3'
services:
   servico1:
     image: nginx:latest
     ports:
       - 8080:8080
     restart: always
   servico2:
     image: nginx:latest
     ports:
       - 8090:8090
     restart: always
